export const MAPS = [
  { id: 1, level: "", name: "Ricarten Town", role: "" },
  { id: 2, level: "", name: "Phillai Town", role: "" },
  { id: 3, level: "", name: "Ruinen Village", role: "" },
  { id: 4, level: "", name: "Navisko Town", role: "" },
  { id: 5, level: "", name: "Atlantis Town", role: "" },
  { id: 6, level: "", name: "Garden of Freedom", role: "" },
  { id: 7, level: "", name: "Bamboo Forest", role: "" },
  { id: 8, level: "", name: "Acacia Grove", role: "" },
  { id: 9, level: "", name: "Road to the Wind", role: "" },
  { id: 10, level: "", name: "Valley of Tranquility", role: "" },
  { id: 11, level: "", name: "Land of Dusk", role: "" },
  { id: 12, level: "", name: "Forest of Spirits", role: "" },
  { id: 13, level: "", name: "Refuge of the Ancients", role: "" },
  { id: 14, level: "", name: "Castle of the Lost", role: "" },
  { id: 15, level: "", name: "Ruinen Village", role: "" },
  { id: 16, level: "", name: "Cursed Land", role: "" },
  { id: 17, level: "", name: "Forgotten Land", role: "" },
  { id: 18, level: "", name: "Oasis", role: "" },
  { id: 19, level: "", name: "Mystery Forest 1", role: "" },
  { id: 20, level: "", name: "Mystery Forest 2", role: "" },
  { id: 21, level: "", name: "Mystery Forest 3", role: "" },
  { id: 22, level: "", name: "Distorted Forest", role: "" },
  { id: 23, level: "", name: "Bellatra", role: "" },
  { id: 24, level: "", name: "Bless Castle", role: "" },
  { id: 25, level: "40", name: "Dungeon 1", role: "" },
  { id: 26, level: "50", name: "Dungeon 2", role: "" },
  { id: 27, level: "55", name: "Battlefield of the Ancients", role: "" },
  { id: 28, level: "55", name: "Forbidden Land", role: "" },
  { id: 29, level: "55", name: "Beehive Cave", role: "" },
  { id: 30, level: "55", name: "Mushroom Cave", role: "" },
  { id: 31, level: "60", name: "Dungeon 3", role: "" },
  { id: 32, level: "65", name: "Sanctuary of Darkness", role: "" },
  { id: 33, level: "70", name: "Greedy Lake", role: "" },
  { id: 34, level: "70", name: "Cursed Temple 1", role: "" },
  { id: 35, level: "75", name: "Cursed Temple 2", role: "" },
  { id: 36, level: "80", name: "Railway of Chaos", role: "" },
  { id: 37, level: "80", name: "Death Cave", role: "" },
  { id: 38, level: "85", name: "Heart of Perum", role: "" },
  { id: 39, level: "90", name: "Eura Village", role: "" },
  { id: 40, level: "90", name: "Gallubia Valley", role: "" },
  { id: 41, level: "95", name: "Frozen Sanctuary", role: "[Hunt]" },
  { id: 42, level: "95", name: "Mystery Desert 1", role: "[Exp]" },
  { id: 43, level: "100", name: "Kelvezu Cave", role: "" },
  { id: 44, level: "100", name: "Lost Island", role: "[Hunt]" },
  { id: 45, level: "100", name: "Mystery Desert 2", role: "[Exp]" },
  { id: 46, level: "105", name: "Battle Town", role: "" },
  { id: 47, level: "105", name: "Lost Temple", role: "[Hunt]" },
  { id: 48, level: "105", name: "Mystery Desert 3", role: "[Exp]" },
  { id: 49, level: "110", name: "Endless Tower 1", role: "[Hunt]" },
  { id: 50, level: "110", name: "Forgotten Temple 1", role: "[Exp]" },
  { id: 51, level: "115", name: "Endless Tower 2", role: "[Hunt]" },
  { id: 52, level: "115", name: "Forgotten Temple 2", role: "[Exp]" },
  { id: 53, level: "120", name: "Cursed Temple 3", role: "[Hunt]" },
  { id: 54, level: "120", name: "Ancient Dungeon 1", role: "[Exp]" },
  { id: 55, level: "124", name: "Endless Tower 3", role: "[Hunt]" },
  { id: 56, level: "124", name: "Ancient Dungeon 2", role: "[Exp]" },
  { id: 57, level: "128", name: "Ice Mine 1", role: "[Hunt]" },
  { id: 58, level: "128", name: "Ancient Dungeon 3", role: "[Exp]" },
  { id: 59, level: "132", name: "Iron Core", role: "[Exp]" },
  { id: 60, level: "132", name: "Death Island", role: "[Hunt]" },
  { id: 61, level: "136", name: "Ancient Weapon", role: "[Hunt]" },
  { id: 62, level: "140", name: "Secret Laboratory", role: "[Hunt]" },
  { id: 63, level: "144", name: "Shadow Sanctuary", role: "[Hunt]" },
];
