export const MAPS = [
  { level: "", name: "Ricarten Town", role: "" },
  { level: "", name: "Phillai Town", role: "" },
  { level: "", name: "Ruinen Village", role: "" },
  { level: "", name: "Navisko Town", role: "" },
  { level: "", name: "Atlantis Town", role: "" },
  {
    level: "",
    name: "Garden of Freedom",
    role: "",
  },
  { level: "", name: "Bamboo Forest", role: "" },
  { level: "", name: "Acacia Grove", role: "" },
  { level: "", name: "Road to the Wind", role: "" },
  {
    level: "",
    name: "Valley of Tranquility",
    role: "",
  },
  { level: "", name: "Land of Dusk", role: "" },
  {
    level: "",
    name: "Forest of Spirits",
    role: "",
  },
  {
    level: "",
    name: "Refuge of the Ancients",
    role: "",
  },
  {
    level: "",
    name: "Castle of the Lost",
    role: "",
  },
  { level: "", name: "Ruinen Village", role: "" },
  { level: "", name: "Cursed Land", role: "" },
  { level: "", name: "Forgotten Land", role: "" },
  { level: "", name: "Oasis", role: "" },
  { level: "", name: "Mystery Forest 1", role: "" },
  { level: "", name: "Mystery Forest 2", role: "" },
  { level: "", name: "Mystery Forest 3", role: "" },
  { level: "", name: "Distorted Forest", role: "" },
  { level: "", name: "Bellatra", role: "" },
  { level: "", name: "Bless Castle", role: "" },
  { level: "40", name: "Dungeon 1", role: "" },
  { level: "50", name: "Dungeon 2", role: "" },
  {
    level: "55",
    name: "Battlefield of the Ancients",
    role: "",
  },
  { level: "55", name: "Forbidden Land", role: "" },
  { level: "55", name: "Beehive Cave", role: "" },
  { level: "55", name: "Mushroom Cave", role: "" },
  { level: "60", name: "Dungeon 3", role: "" },
  {
    level: "65",
    name: "Sanctuary of Darkness",
    role: "",
  },
  { level: "70", name: "Greedy Lake", role: "" },
  {
    level: "70",
    name: "Cursed Temple 1",
    role: "",
  },
  {
    level: "75",
    name: "Cursed Temple 2",
    role: "",
  },
  {
    level: "80",
    name: "Railway of Chaos",
    role: "",
  },
  { level: "80", name: "Death Cave", role: "" },
  { level: "85", name: "Heart of Perum", role: "" },
  { level: "90", name: "Eura Village", role: "" },
  {
    level: "90",
    name: "Gallubia Valley",
    role: "",
  },
  {
    level: "95",
    name: "Frozen Sanctuary",
    role: "[Hunt]",
  },
  {
    level: "95",
    name: "Mystery Desert 1",
    role: "[Exp]",
  },
  { level: "100", name: "Kelvezu Cave", role: "" },
  {
    level: "100",
    name: "Lost Island",
    role: "[Hunt]",
  },
  {
    level: "100",
    name: "Mystery Desert 2",
    role: "[Exp]",
  },
  { level: "105", name: "Battle Town", role: "" },
  {
    level: "105",
    name: "Lost Temple",
    role: "[Hunt]",
  },
  {
    level: "105",
    name: "Mystery Desert 3",
    role: "[Exp]",
  },
  {
    level: "110",
    name: "Endless Tower 1",
    role: "[Hunt]",
  },
  {
    level: "110",
    name: "Forgotten Temple 1",
    role: "[Exp]",
  },
  {
    level: "115",
    name: "Endless Tower 2",
    role: "[Hunt]",
  },
  {
    level: "115",
    name: "Forgotten Temple 2",
    role: "[Exp]",
  },
  {
    level: "120",
    name: "Cursed Temple 3",
    role: "[Hunt]",
  },
  {
    level: "120",
    name: "Ancient Dungeon 1",
    role: "[Exp]",
  },
  {
    level: "124",
    name: "Endless Tower 3",
    role: "[Hunt]",
  },
  {
    level: "124",
    name: "Ancient Dungeon 2",
    role: "[Exp]",
  },
  {
    level: "128",
    name: "Ice Mine 1",
    role: "[Hunt]",
  },
  {
    level: "128",
    name: "Ancient Dungeon 3",
    role: "[Exp]",
  },
  {
    level: "132",
    name: "Iron Core",
    role: "[Exp]",
  },
  {
    level: "132",
    name: "Death Island",
    role: "[Hunt]",
  },
  {
    level: "136",
    name: "Ancient Weapon",
    role: "[Hunt]",
  },
  {
    level: "140",
    name: "Secret Laboratory",
    role: "[Hunt]",
  },
  {
    level: "144",
    name: "Shadow Sanctuary",
    role: "[Hunt]",
  },
];
